version: '3.9'

services:
  db:
    image: mariadb:latest
    container_name: database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_HOST: 103.226.139.120
      MYSQL_DATABASE: test_djangodocker
      MYSQL_USER: dev
      MYSQL_PASSWORD: devatsafebox
      MYSQL_ROOT_PASSWORD: devatsafebox
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - mariadb_data:/var/lib/mysql
  app:
    # image: test-docker:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8009 --noreload
    container_name: main
    image: app:django
    ports:
      - "8009:8009"
    depends_on:
      - db 
    links:
      - db

volumes:
  mariadb_data: